# Generated by Django 4.2.4 on 2023-08-25 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('w2w_app', '0003_genre_movie_platform_ratingcomment_movie_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='website_link',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='directed_by', to='w2w_app.person'),
        ),
    ]
